import type { Scenario } from '../types';

const local = (...cmds: string[]) => cmds.map((cmd) => ({ target: 'local' as const, cmd }));

/**
 * Named, shared starting points. A lesson runs exactly one of these, once, from
 * an empty world — so jumping between lessons in any order is idempotent, and
 * the graph always matches what the lesson text describes.
 */
export const SCENARIOS: Scenario[] = [
  {
    id: 'empty',
    description: 'An empty folder. Nothing here is a repository yet.',
    script: [],
  },
  {
    id: 'fresh-repo',
    description: 'An initialised repository with no commits yet.',
    script: local('git init'),
  },
  {
    id: 'one-commit',
    description: 'A repository with a single commit containing README.md.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
    ),
  },
  {
    id: 'small-history',
    description: 'Three commits on main, each building on the last.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'echo "console.log(1)" > app.js',
      'git add app.js',
      'git commit -m "Add app.js"',
      'echo "console.log(2)" > app.js',
      'git commit -am "Update app.js"',
    ),
  },
  {
    id: 'dirty-history',
    description: 'Three commits, plus an edit you have not committed yet.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'echo "console.log(1)" > app.js',
      'git add app.js',
      'git commit -m "Add app.js"',
      'echo "console.log(2)" > app.js',
      'git commit -am "Update app.js"',
      'echo "console.log(3) // work in progress" > app.js',
    ),
  },
  {
    id: 'two-branches',
    description: 'main and a feature branch, both pointing at the same commit.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'echo "console.log(1)" > app.js',
      'git add app.js',
      'git commit -m "Add app.js"',
      'git branch feature',
    ),
  },
  {
    id: 'diverged-branches',
    description: 'main and feature have each moved on since they split.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git switch -c feature',
      'echo "the feature" > feature.txt',
      'git add feature.txt',
      'git commit -m "Add the feature"',
      'git switch main',
      'echo "docs" > docs.md',
      'git add docs.md',
      'git commit -m "Add docs"',
    ),
  },
  {
    id: 'conflicting-branches',
    description: 'main and feature have both edited the same line of config.txt.',
    script: local(
      'git init',
      'echo "colour = blue" > config.txt',
      'git add config.txt',
      'git commit -m "Add config"',
      'git switch -c feature',
      'echo "colour = green" > config.txt',
      'git commit -am "Use green"',
      'git switch main',
      'echo "colour = red" > config.txt',
      'git commit -am "Use red"',
    ),
  },
  {
    id: 'published',
    description: 'A repository with a remote called origin, already in sync.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
    ),
  },
  {
    id: 'remote-ahead',
    description: 'A teammate has pushed to origin/main since you last looked.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'teammate push main CHANGELOG.md "First release" "Add a changelog"',
    ),
  },
  {
    id: 'diverged-from-remote',
    description: 'You have a local commit, and a teammate has pushed a different one.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'teammate push main CHANGELOG.md "First release" "Add a changelog"',
      'echo "console.log(1)" > app.js',
      'git add app.js',
      'git commit -m "Add app.js"',
    ),
  },
  {
    id: 'feature-pushed',
    description: 'A feature branch with one commit, already pushed to origin.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'git switch -c add-login',
      'echo "login()" > login.js',
      'git add login.js',
      'git commit -m "Add login"',
      'git push -u origin add-login',
    ),
  },
  {
    id: 'boss-level',
    description:
      'A teammate pushed to main, you have a local commit, and uncommitted work in the tree.',
    script: local(
      'git init',
      'echo "colour = blue" > config.txt',
      'echo "project notes" > notes.md',
      'git add .',
      'git commit -m "Add config and notes"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'teammate push main config.txt "colour = red" "Switch to red"',
      'echo "colour = green" > config.txt',
      'echo "console.log(1)" > app.js',
      'git add config.txt app.js',
      'git commit -m "Add app.js and recolour config"',
      'echo "project notes\n\nhalf-finished thought" > notes.md',
    ),
  },
  {
    id: 'feature-pushed-messy',
    description: 'A feature branch with three scrappy commits, already pushed for review.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'git switch -c add-login',
      'echo "login()" > login.js',
      'git add login.js',
      'git commit -m "add login"',
      'echo "login() // fixed typo" > login.js',
      'git commit -am "fix"',
      'echo "login() // fixed typo" > login.js',
      'echo "// TODO: tests" >> login.js',
      'git commit -am "wip"',
      'git push -u origin add-login',
    ),
  },
  {
    id: 'feature-merged',
    description: 'A feature branch whose pull request has already been merged on the server.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'git switch -c add-login',
      'echo "login()" > login.js',
      'git add login.js',
      'git commit -m "Add login"',
      'git push -u origin add-login',
      'gh pr create --title "Add login"',
      'gh pr merge',
    ),
  },
  {
    id: 'feature-needs-rebase',
    description:
      'main and your pushed feature branch have both moved on, and a teammate has added to the feature.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'git switch -c add-login',
      'echo "login()" > login.js',
      'git add login.js',
      'git commit -m "Add login"',
      'git push -u origin add-login',
      'teammate push add-login login.js "login() // reviewed by Sam" "Address review comments"',
      'git switch main',
      'echo "docs" > docs.md',
      'git add docs.md',
      'git commit -m "Add docs"',
      'git push',
      'git switch add-login',
    ),
  },
  {
    id: 'legacy-master',
    description: 'A repository created before main was the default — it is on master.',
    script: local(
      'git init',
      'echo "# Legacy project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'git branch -m main master',
    ),
  },
  {
    id: 'release-tagged',
    description: 'A v1.0 tag, with two commits landed since the release.',
    script: local(
      'git init',
      'echo "version 1.0" > app.js',
      'git add app.js',
      'git commit -m "Release 1.0"',
      'git tag -a v1.0 -m "Release 1.0"',
      'echo "version 1.1" > app.js',
      'git commit -am "Add the export feature"',
      'echo "version 1.2" > app.js',
      'git commit -am "Fix the export crash"',
    ),
  },
  {
    id: 'fixup-history',
    description: 'Two feature commits on main; ready to have a mistake folded in.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'echo "console.log(1)" > app.js',
      'git add app.js',
      'git commit -m "Add app.js"',
      'echo "TODO" > notes.txt',
      'git add notes.txt',
      'git commit -m "Add notes"',
    ),
  },
  {
    id: 'dangling-commit',
    description: 'A commit that was reset away and is now unreachable from any branch.',
    script: local(
      'git init',
      'echo "one" > a.txt',
      'git add a.txt',
      'git commit -m "First commit"',
      'echo "two" > a.txt',
      'git commit -am "Second commit"',
      'git reset --hard HEAD~1',
    ),
  },
  {
    id: 'leaked-secret',
    description: 'A repository with a live API key committed straight into history.',
    script: local(
      'git init',
      'echo "API_KEY=sk-live-1234567890" > secrets.env',
      'echo "# My Project" > README.md',
      'git add secrets.env README.md',
      'git commit -m "Add config and secrets"',
    ),
  },
  {
    id: 'untracked-mess',
    description: 'A committed .gitignore, plus a scratch file and an ignored log file.',
    script: local(
      'git init',
      'echo "# My Project" > README.md',
      'git add README.md',
      'git commit -m "Initial commit"',
      'echo "*.log" > .gitignore',
      'git add .gitignore',
      'git commit -m "Ignore log files"',
      'echo "scratch work" > notes.txt',
      'echo "noisy output" > debug.log',
    ),
  },
  {
    id: 'blame-history',
    description: 'A file with lines written by two different people.',
    script: local(
      'git init',
      'echo "Line one" > story.txt',
      'git add story.txt',
      'git commit -m "Start the story"',
      'git remote add origin https://github.com/you/project.git',
      'git push -u origin main',
      'teammate push main story.txt "Line one\nLine two, by Sam" "Add a second line"',
      'git pull',
    ),
  },
  {
    id: 'bisect-bug',
    description: 'Eight commits on main; one of them broke app.txt and it has been broken since.',
    script: local(
      'git init',
      'echo "status: OK v1" > app.txt',
      'git add app.txt',
      'git commit -m "Start the app"',
      'echo "status: OK v2" > app.txt',
      'git commit -am "Tidy the output"',
      'echo "status: OK v3" > app.txt',
      'git commit -am "Add a header"',
      'echo "status: OK v4" > app.txt',
      'git commit -am "Tweak the header"',
      'echo "status: BROKEN v5" > app.txt',
      'git commit -am "Refactor the status line"',
      'echo "status: BROKEN v6" > app.txt',
      'git commit -am "Continue refactor"',
      'echo "status: BROKEN v7" > app.txt',
      'git commit -am "Rename a variable"',
      'echo "status: BROKEN v8" > app.txt',
      'git commit -am "Update docs"',
    ),
  },
];

export const SCENARIOS_BY_ID: Record<string, Scenario> =
  Object.fromEntries(SCENARIOS.map((s) => [s.id, s]));
